// Code generated by schema-generate. DO NOT EDIT.

package main

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Dimensions
type Dimensions struct {
	Height float64 `json:"height" bson:"height"`
	Length float64 `json:"length" bson:"length"`
	Width  float64 `json:"width" bson:"width"`
}

// LongitudeAndLatitude A geographical coordinate on a planet (most commonly Earth).
type LongitudeAndLatitude struct {
	Latitude  float64 `json:"latitude" bson:"latitude"`
	Longitude float64 `json:"longitude" bson:"longitude"`
}

// Product A product from Acme's catalog
type Product struct {
	Dimensions *Dimensions         `json:"dimensions,omitempty" bson:"dimensions,omitempty"`
	ObjectId   *primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`

	// The price of the product
	Price float64 `json:"price" bson:"price"`

	// The unique identifier for a product
	ProductId int `json:"productId" bson:"productId"`

	// Name of the product
	ProductName string `json:"productName" bson:"productName"`

	// Tags for the product
	Tags []string `json:"tags,omitempty" bson:"tags,omitempty"`

	// Coordinates of the warehouse where the product is located.
	WarehouseLocation *LongitudeAndLatitude `json:"warehouseLocation,omitempty" bson:"warehouseLocation,omitempty"`
}
