// Code generated by schema-generate. DO NOT EDIT.

package main

// Address Address
type Address struct {

	// House Number
	HouseNumber *int `json:"houseNumber,omitempty"`

	// Address 1
	Street *string `json:"street,omitempty"`
}

// Example An example JSON Schema
type Example struct {
	Address *Address `json:"address,omitempty"`
	Name    *string  `json:"name,omitempty"`
	Status  *Status  `json:"status,omitempty"`
}

// FavouriteCat The favourite cat.
type FavouriteCat string

const (
	FavouriteCatA FavouriteCat = "A"
	FavouriteCatB FavouriteCat = "B"
	FavouriteCatC FavouriteCat = "C"
)

// Status
type Status struct {

	// The favourite cat.
	FavouriteCat FavouriteCat `json:"favouriteCat,omitempty"`
}
