// Code generated by schema-generate. DO NOT EDIT.

package main

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"time"
)

// CancelTariffication
type CancelTariffication struct {

	// Информация о клиенте
	Customer *ChargingHistoryEventCustomer `json:"customer" bson:"customer"`

	// Дата-время события в ISO-8601
	EventDate time.Time `json:"eventDate" bson:"eventDate"`

	// Идентификатор события, уникальный в разрезе source
	EventId   string              `json:"eventId" bson:"eventId"`
	EventType EventType           `json:"eventType" bson:"eventType"`
	ObjectId  *primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`

	// Идентификатор продукта
	ProductId string `json:"productId" bson:"productId"`

	// Тарифная компонента
	TariffComponent *TariffComponent `json:"tariffComponent" bson:"tariffComponent"`
}

// Card
type Card struct {

	// Месяц действия карты (MM)
	ExpiryMonth int `json:"expiryMonth" bson:"expiryMonth"`

	// Год действия карты (YYYY)
	ExpiryYear int `json:"expiryYear" bson:"expiryYear"`

	// Маскированный номер карты
	MaskedPan string `json:"maskedPan" bson:"maskedPan"`

	// Тип платежной системы (VISA, MASTERCARD, MAESTRO, MIR, CUP и др.)
	Type string `json:"type" bson:"type"`
}

// ChangePaymentMethod
type ChangePaymentMethod struct {

	// Токен оплаты для ECHRG
	ChargingTokenId *string `json:"chargingTokenId,omitempty" bson:"chargingTokenId,omitempty"`

	// Информация о клиенте
	Customer *ChargingHistoryEventCustomer `json:"customer,omitempty" bson:"customer,omitempty"`

	// Дата-время события в ISO-8601
	EventDate time.Time `json:"eventDate" bson:"eventDate"`

	// Идентификатор события, уникальный в разрезе source
	EventId   string    `json:"eventId" bson:"eventId"`
	EventType EventType `json:"eventType" bson:"eventType"`

	// Выбранный способ оплаты
	NewPaymentMethod *PaymentMethod      `json:"newPaymentMethod" bson:"newPaymentMethod"`
	ObjectId         *primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`

	// Идентификатор продукта
	ProductId string `json:"productId" bson:"productId"`
}

// ChargingHistoryEventCustomer
type ChargingHistoryEventCustomer struct {

	// Идентификатор клиента
	Id *string `json:"id,omitempty" bson:"id,omitempty"`

	// Номер телефона
	Msisdn *string `json:"msisdn,omitempty" bson:"msisdn,omitempty"`
}

// EventType
type EventType string

const (
	EventTypeCanceltariffication        EventType = "CancelTariffication"
	EventTypeChangepaymentmethod        EventType = "ChangePaymentMethod"
	EventTypeCompletetariffication      EventType = "CompleteTariffication"
	EventTypeDeactivatetariffication    EventType = "DeactivateTariffication"
	EventTypePendingcanceltariffication EventType = "PendingCancelTariffication"
	EventTypePromotionaction            EventType = "PromotionAction"
	EventTypeRecurringchargefailed      EventType = "RecurringChargeFailed"
	EventTypeRecurringchargesuccess     EventType = "RecurringChargeSuccess"
	EventTypeResumetariffication        EventType = "ResumeTariffication"
	EventTypeStarttariffication         EventType = "StartTariffication"
	EventTypeStoptariffication          EventType = "StopTariffication"
)

// PaymentMethod
type PaymentMethod struct {
	Card *Card `json:"card,omitempty" bson:"card,omitempty"`

	// Замаскированное отображение
	MaskedName *string `json:"maskedName,omitempty" bson:"maskedName,omitempty"`

	// Маскированный номер телефона
	MaskedPhone *string `json:"maskedPhone,omitempty" bson:"maskedPhone,omitempty"`

	// Состояние платежного токена. Возможные значения: creating, active, declined, disabled. Справочник - TokensStatus на странице https://confluence.mts.ru/pages/viewpage.action?pageId=400664570
	State string `json:"state" bson:"state"`

	// Идентификатор токена
	TokenId *string `json:"tokenId,omitempty" bson:"tokenId,omitempty"`

	// Тип платёжного инструмента: BANK_CARD, PERSONAL_ACCOUNT
	Type string `json:"type" bson:"type"`
}

// TariffComponent
type TariffComponent struct {

	// Идентификатор основной тарифной компоненты
	Id string `json:"id" bson:"id"`

	// Тип тарифной компоненты
	Type TariffSpecificationsType `json:"type" bson:"type"`
}

// TariffSpecificationsType
type TariffSpecificationsType string

const (
	TariffSpecificationsTypeSubscription       TariffSpecificationsType = "SUBSCRIPTION"
	TariffSpecificationsTypeInstallment        TariffSpecificationsType = "INSTALLMENT"
	TariffSpecificationsTypeDeviceSubscription TariffSpecificationsType = "DEVICE_SUBSCRIPTION"
	TariffSpecificationsTypeSale               TariffSpecificationsType = "SALE"
	TariffSpecificationsTypeOverduePenalty     TariffSpecificationsType = "OVERDUE_PENALTY"
	TariffSpecificationsTypeDeviceConditionFee TariffSpecificationsType = "DEVICE_CONDITION_FEE"
	TariffSpecificationsTypeAction             TariffSpecificationsType = "ACTION"
)
